### ISSUE TITLE
CDI lifecycle methopds

### ISSUE THREAD

**Issue by hhiden** [project-streamzi/kafka-cdi#4]
The standard @PostCreate, @PreDestroy etc lifecycle methods are not called on an annotated beans

**Comment by matzew** [comment]
@hhiden how does your bean look like ?

**Comment by hhiden** [comment]
@ApplicationScoped
@KafkaConfig(bootstrapServers = "#{KAFKA_SERVICE_HOST}:#{KAFKA_SERVICE_PORT}")
public class CustomerRecordMongoPersist {
    private static final Logger logger = Logger.getLogger(CustomerRecordMongoPersist.class.getName());


    public CustomerRecordMongoPersist() {

    }
    
    /** Respond to customer profile updates */
    @Consumer(topics = "profile.out", groupId = "1")
    public void onMessage(String key, String value){

        
    }
    
    public void postConstruct(){
        logger.info("postConstruct");
    }
    
    @PostConstruct
    public void create(){
        logger.info(“Create");
    }
    
    @PreDestroy
    public void close(){
        logger.info(“Close");
    }
}

**Comment by matzew** [comment]
works, but problem was that there were multiple `KafkaConfig` instances
